apiVersion: v1
kind: Service
metadata: 
  name: mongo-service
  namespace: db-eriklvicente
spec: 
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP


  